// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudQEh7hiw5bSv5kfgHSVRqVkxePZ2d0k',
    appId: '1:537606692052:web:700e9810a0f8c3bf3daf41',
    messagingSenderId: '537606692052',
    projectId: 'project-shop-xd',
    authDomain: 'project-shop-xd.firebaseapp.com',
    storageBucket: 'project-shop-xd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUI--uraUU-W8NC87NY5zMc8ZQ5Hoiwwo',
    appId: '1:537606692052:android:62ae9d1ee92234c53daf41',
    messagingSenderId: '537606692052',
    projectId: 'project-shop-xd',
    storageBucket: 'project-shop-xd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDel_Z1YUfSYVkp0RCAClEDmEpr2lZyCBo',
    appId: '1:537606692052:ios:dd4638841957edd53daf41',
    messagingSenderId: '537606692052',
    projectId: 'project-shop-xd',
    storageBucket: 'project-shop-xd.appspot.com',
    iosBundleId: 'com.example.projectShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDel_Z1YUfSYVkp0RCAClEDmEpr2lZyCBo',
    appId: '1:537606692052:ios:dd4638841957edd53daf41',
    messagingSenderId: '537606692052',
    projectId: 'project-shop-xd',
    storageBucket: 'project-shop-xd.appspot.com',
    iosBundleId: 'com.example.projectShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudQEh7hiw5bSv5kfgHSVRqVkxePZ2d0k',
    appId: '1:537606692052:web:522a8732a3f6e5033daf41',
    messagingSenderId: '537606692052',
    projectId: 'project-shop-xd',
    authDomain: 'project-shop-xd.firebaseapp.com',
    storageBucket: 'project-shop-xd.appspot.com',
  );
}
